## Append samples of your project ##
resources:
- headscale_v1beta2_headscale.yaml
- headscale_v1beta2_headscaleuser.yaml
- headscale_v1beta2_headscalepreauthkey.yaml
- headscale_v1beta2_headscaleautoapprover.yaml
- headscale_v1beta2_clusterheadscale.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
